VAGRANT_API_VERSION = "2"
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "nfs-server" do |nfs|
    nfs.vm.hostname = "nfs-server"
    nfs.vm.network "private_network", ip: "192.168.56.10"
    nfs.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "docker-master" do |master|
    master.vm.hostname = "docker-master"
    master.vm.network "private_network", ip: "192.168.56.11"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "docker-node1" do |node|
    node.vm.hostname = "docker-node1"
    node.vm.network "private_network", ip: "192.168.56.12"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "docker-node2" do |node|
    node.vm.hostname = "docker-node2"
    node.vm.network "private_network", ip: "192.168.56.13"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "docker-node3" do |node|
    node.vm.hostname = "docker-node3"
    node.vm.network "private_network", ip: "192.168.56.14"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end
  config.vm.define "docker-node4" do |node|
    node.vm.hostname = "docker-node4"
    node.vm.network "private_network", ip: "192.168.56.15"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end      
end
