version: '3.8'

services:
  nginx:
    image: silvemerson/site-demo-labs:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.role == nginx-docker
      restart_policy:
        condition: any
